// <auto-generated />
namespace MyMovies.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class OverallMigration01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverallMigration01));
        
        string IMigrationMetadata.Id
        {
            get { return "202104272009518_OverallMigration01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
